Check HW_8
anattoly/exeptions pull request #1
Opened 2019-07-17 16:21 UTC by anattoly

Check my code, plaese.

2019-07-23 14:13 UTC, i-kovalyshyn commented
1. you have an unused method execStackOverflow
2.you should do more securable class Server

2019-07-25 10:44 UTC, i-kovalyshyn approved these changes

2019-07-25 10:44 UTC, i-kovalyshyn approved these changes

2019-08-01 08:42 UTC, OleksandrTsyhankov approved these changes

2019-08-06 07:03 UTC, NickRbk requested changes
1. Use try-with-resources to autoclose resources
2. Use method equalsIgnoreCase to simplify this statement ``s.toLowerCase().equals(new StringBuilder(s).reverse().toString().toLowerCase())``

2019-08-06 09:02 UTC, anattoly commented
> 1. Use try-with-resources to autoclose resources
> 2. Use method equalsIgnoreCase to simplify this statement `s.toLowerCase().equals(new StringBuilder(s).reverse().toString().toLowerCase())`

Maked requested changes

2019-08-10 18:15 UTC, merged